//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 1.5.0)
//  https://docs.swiftylaun.ch/module/app
//

import InAppPurchaseKit
import NotifKit
import SharedKit
import SupabaseKit
import SwiftUI

struct ContentView: View {

	var body: some View {
		TabView {
            
            Tab("", systemImage: "house") {
                HomeView()
            }

			// Example view on how to access the Database.
			Tab("", systemImage: "bolt") {
				DatabaseExampleView()
			}

			// Pre-made Settings View for easy native-looking settings screen.
			Tab("", systemImage: "person") {
				SettingsView()
			}

			#if DEBUG

				TabSection("DEBUG ONLY") {
					// Use this to create quick settings and toggles to streamline the development process
					Tab("", systemImage: "lock.shield") {
						DeveloperSettingsView()
					}
				}

			#endif
		}

		.tabViewStyle(.sidebarAdaptable)
		.tabViewSidebarHeader {
			Text("SwiftyLaunch App")
				.font(.title)
				.bold()
				.frame(maxWidth: .infinity, alignment: .leading)

		}

	}
}

#Preview {
	ContentView()
		.environmentObject(InAppPurchases())
}
